### ISSUE TITLE
cosigned: chart requires private key?

### ISSUE THREAD

**Issue by ahmetb** [sigstore/helm-charts#29]
https://github.com/sigstore/helm-charts/tree/72bac9e947fba3bff31d59ad124a277d92348a5f/charts/cosigned#:~:text=kubectl%20create%20secret%20generic%20mysecret%20-n%20%5C%0Acosign-system%20--from-file%3Dcosign.pub%3D./cosign.pub%20%5C%0A--from-file%3Dcosign.key%3D./cosign.key%20%5C%0A--from-literal%3Dcosign.password%3D%24COSIGN_PASSWORD

I am trying to understand why the cosigned webhook requires my private key and password. I thought those should not leave my computer. It would be good to clarify in the instructions, I think.

**Comment by airadier** [comment]
I came across the charts and wondering exactly the same thing.

**Comment by hectorj2f** [comment]
Yes, it makes no sense because cosigned only uses the public key, https://github.com/sigstore/cosign/blob/main/pkg/cosign/kubernetes/webhook/validation.go#L93.

**Comment by hectorj2f** [comment]
There are two problems here, one is related to the documentation which is not using the correct property name. On the other hand, the webhook is relying on the generated secret https://github.com/sigstore/helm-charts/blob/main/charts/cosigned/templates/webhook/cosign_secret.yaml, instead of a secret name itself.
