### ISSUE TITLE
Shouldn't the Chart.lock files be committed to pin the dependencies?

### ISSUE THREAD

**Issue by marcofranssen** [sigstore/helm-charts#298]
**Question**

Usually it is a good practice to commit lock files to ensure we pin to exactly the same version of a release. E.g. a tag could be replaced and therefore silently install another dependency.

I would propose to remove the exclusion from the Chart.lock from the .gitignore and pin all charts with dependencies by running.

```shell
helm dependency build
```

This will download a tgz, which we should add to the .gitignore.

Happy to provide a PR if you agree.

**Comment by cpanato** [comment]
sounds good, go ahead

**Comment by sabre1041** [comment]
@marcofranssen Ive gone back/forth on whether they should be committed or not. Mainly because at the early stages of the project, there were a lot of pieces still in flux.

However, given that there is relative stability at this time, its a good idea to move forward with that plan.

Thanks for contributing this and some of the other areas that you have proposed for the repository!
